### ISSUE TITLE
连接go-fastdfs服务失败!请检查服务地址是否正确!

### ISSUE THREAD

**Issue by baiooy** [perfree/go-fastdfs-web#10]
请问这个问题怎么解决，在那个文件里面修改，我用的外网IP，填写IP后也提示这个

**Comment by baiooy** [comment]
HttpUtil.get(urlPath+GoFastDfsApi.STAT)   这个怎样才可以访问？

**Comment by yyycccqqq** [comment]
这个问题怎么解决？
