### ISSUE TITLE
web端无法查看图片

### ISSUE THREAD

**Issue by Raylively** [perfree/go-fastdfs-web#13]
go-fastdfsweb突然看不到图片了，点击查看图片也没有报错，就出现一个偏黑色的遮罩层

**Comment by perfree** [comment]
查看下web和gofastdfs版本是否对应,网络是否通畅

**Comment by Raylively** [comment]
go-fastdfs-web端能上传下载，下载的图片也可以直接用网址访问到，就是不能直接再go-fastdfs-web端展示

**Comment by perfree** [comment]
gofastdfs版本和web端版本分别是多少?web端要和gofastdfs版本对应,期间gofastdfs调整了一些路径
![image](https://user-images.githubusercontent.com/34746579/67731596-b5177400-fa33-11e9-91a1-1b2898f330b4.png)
