### ISSUE TITLE
定义要 上传文件临时目录吗？

### ISSUE THREAD

**Issue by qinkangdeid** [perfree/go-fastdfs-web#2]
不错的项目 感谢大佬 有个问题
就是一定要 上传文件临时目录吗？
我点击选择文件 点击上传 他是去临时目录拿文件？可是临时文件肯定是空的啊  我是随机在电脑上选的图片（文件）
![image](https://user-images.githubusercontent.com/17582522/58311556-d13b3780-7e3b-11e9-8123-29a1c7ca7c3d.png)

**Comment by perfree** [comment]
会先将文件保存至临时目录，之后上传至服务器，主要为了后期的权限处理

**Comment by qinkangdeid** [comment]
了解
