### ISSUE TITLE
goFastDfsWeb.sh 文件为dos格式格式导致启动失败

### ISSUE THREAD

**Issue by zhangleijie** [perfree/go-fastdfs-web#21]
楼主， 我从github上下载的go-fastdfs-web-1.3.4.tar.gz文件 在centos7上启动时报错
-bash: ./goFastDfsWeb.sh: /bin/bash^M: bad interpreter: No such file or directory

经过排查需要执行sed -i "s/\r//" goFastDfsWeb.sh 命令后就可以启动了，原因是这个文件中存在dos格式编码
可参考 https://blog.csdn.net/hxpjava1/article/details/79711710

[root@srvr1 go-fastdfs-web]# ./goFastDfsWeb.sh start
-bash: ./goFastDfsWeb.sh: /bin/bash^M: bad interpreter: No such file or directory
[root@srvr1 go-fastdfs-web]# ^C
[root@srvr1 go-fastdfs-web]# sed -i "s/\r//" goFastDfsWeb.sh 
[root@srvr1 go-fastdfs-web]# ./goFastDfsWeb.sh start
Start go-fastdfs-web.jar success...
[root@srvr1 go-fastdfs-web]# ps -ef | grep java
root     12016     1 99 21:52 pts/3    00:00:19 java -jar go-fastdfs-web.jar
root     12041 10794  0 21:52 pts/3    00:00:00 grep --color=auto java
[root@srvr1 go-fastdfs-web]# ls

**Comment by imyaba** [comment]
linux  centos7 下需要转变启动文件编码
vi goFastDfsWeb.sh 
执行  : set ff=unix  将格式保存为unix 格式
就可以执行了
