### ISSUE TITLE
白名单问题

### ISSUE THREAD

**Issue by fanjialing** [perfree/go-fastdfs-web#35]
访问go-fastdfs安装页面,填好各种信息后,提示go-fastdfs连接失败,请检查是否配置白名单

**Comment by wys1010** [comment]
我也遇到这问题了，配置了白名单死活不行

**Comment by Sanbingduizhang** [comment]
我是用docker安装的web管理页面，如果用docker安装的话，还需要把docker中的地址(如：172.17.0.3)，添加到白名单中，就可以访问了
