### ISSUE TITLE
账号配置，点击安装报错

### ISSUE THREAD

**Issue by xiaohezi205** [perfree/go-fastdfs-web#49]
![image](https://user-images.githubusercontent.com/84753977/119424922-ffa8c180-bd38-11eb-9976-767dfab2468f.png)
![image](https://user-images.githubusercontent.com/84753977/119424947-0c2d1a00-bd39-11eb-8a91-839f14791d45.png)

**Comment by perfree** [comment]
请检查数据库文件是否存在或者是项目文件夹否有操作权限
