### ISSUE TITLE
请问在哪里可以查看文件fastdfs服务器的地址并修改？

### ISSUE THREAD

**Issue by cappuccino5** [perfree/go-fastdfs-web#5]
请问在哪里可以查看文件fastdfs服务器的地址并修改它，因为我文件服务器地址变更了，导致web端也无法使用

**Comment by cappuccino5** [comment]
这个问题解决了，在集群里面

**Comment by baiooy** [comment]
那个文件？fdfs.trackerList=47.xxx.xxx.xxx:22122 ??这几个文件吗
