### ISSUE TITLE
安装注册最后阶段卡住

### ISSUE THREAD

**Issue by 838239178** [perfree/go-fastdfs-web#52]
![image](https://user-images.githubusercontent.com/55338151/125891198-8be9440a-cdc2-4e78-bb29-ef9778bf1bb0.png)
日志停留在关闭 Sqlsession
```
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@14856e56]

```

**Comment by kidbei** [comment]
没有建表，也没看到建表脚本

**Comment by perfree** [comment]
是在哪个环境安装的?win/linux/docker

**Comment by 838239178** [comment]
> 是在哪个环境安装的?win/linux/docker

linux

**Comment by perfree** [comment]
已定位问题,稍后会修复下,感谢反馈~

**Comment by perfree** [comment]
麻烦试下v1.3.6,验证是否修复,如依然出现该问题,方便的话可以提供下log文件

**Comment by 838239178** [comment]
> 麻烦试下v1.3.6,验证是否修复,如依然出现该问题,方便的话可以提供下log文件

有空就测试

**Comment by 838239178** [comment]
@perfree 成功登录 但是首页报错了 #57
