### ISSUE TITLE
能否提供个dockerfile

### ISSUE THREAD

**Issue by bnubobby** [perfree/go-fastdfs-web#6]
安装还是有点麻烦，能提供个dockerfile 就好了
执行 ./goFastDfsWeb.sh start 后，无论 是否成功，都显示 success
还需要 ./goFastDfsWeb.sh status 才能知道是否真正启动成功
失败的时候，不知道去哪里找日志，有点折腾

**Comment by perfree** [comment]
下个版本提供

**Comment by fjnetinfo** [comment]
请问下个版本在哪里。
