### ISSUE TITLE
docker版本识别不了新的go-fastdfs

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [perfree/go-fastdfs-web#64]
您好，docker版本识别不了新的go-fastdfs，非docker版本可以，截图如下
![33](https://user-images.githubusercontent.com/7458713/162648920-a99cee19-209c-4a12-b2db-d4ea4f1f18c2.png)

**Comment by shanhai2333** [comment]
白名单里面放行web这个docker127那个ip
