### ISSUE TITLE
文件列表报错：500

### ISSUE THREAD

**Issue by weiluoliang** [perfree/go-fastdfs-web#8]
![image](https://user-images.githubusercontent.com/19885121/60661167-fc2d9800-9e8b-11e9-92b5-7b90d39f63b2.png)
![image](https://user-images.githubusercontent.com/19885121/60661181-064f9680-9e8c-11e9-9bf9-d6b77ba1b8e5.png)

感觉很奇怪 怎么会报这个错误

**Comment by perfree** [comment]
查看下go-fastdfs的版本，v1.2.8之前不可使用文件列表功能，v1.3及v1.3之后请使用最新版

**Comment by weiluoliang** [comment]
嗯 我切换到最新版本就可以看文件了，谢谢
