### ISSUE TITLE
IP白名单不能支持ip段吗

### ISSUE THREAD

**Issue by yangyang198599** [perfree/go-fastdfs-web#9]

**Comment by perfree** [comment]
ip段？？

**Comment by yangyang198599** [comment]
like 10.10.0.0/24

**Comment by perfree** [comment]
不支持，web是调具体接口实现的，只需配置一个ip即可，利用gofastdfs的同步，一个ip即可获取整个集群的信息

**Comment by yangyang198599** [comment]
谢谢，再麻烦问一下，host只能用ip吗？域名行不行？因为在k8s环境下ip是不能固定的。尝试了一下连接失败了

**Comment by perfree** [comment]
web是可以的，但是gofastdfs白名单仅支持ip，你可以将web放到任意一台有gofastdfs的服务器上，地址配置127.0.0.1就行了
